CREATE TABLE album(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title TEXT NOT NULL,
  artist_id INTEGER NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT artist_album FOREIGN KEY (artist_id) REFERENCES artist (id)
) STRICT;

CREATE TABLE artist(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE customer(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title TEXT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL,
  post_code TEXT NOT NULL,
  phone TEXT NOT NULL,
  fax TEXT,
  email TEXT NOT NULL,
  employee_id INTEGER,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employee_customer FOREIGN KEY (employee_id) REFERENCES employee (id)
) STRICT;

CREATE TABLE employee(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title TEXT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_of_birth TEXT NOT NULL,
  hire_date TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL,
  post_code TEXT NOT NULL,
  phone TEXT NOT NULL,
  fax TEXT,
  email TEXT NOT NULL,
  supervisor_id INTEGER NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employee_employee
    FOREIGN KEY (supervisor_id) REFERENCES employee (id)
) STRICT;

CREATE TABLE genre(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE invoice(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  invoice_date TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL,
  post_code TEXT NOT NULL,
  total INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  employee_id INTEGER NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customer_invoice FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT employee_invoice FOREIGN KEY (employee_id) REFERENCES employee (id)
) STRICT;

CREATE TABLE invoice_item(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  quantity INTEGER NOT NULL,
  price INTEGER NOT NULL,
  invoice_id INTEGER NOT NULL,
  track_id INTEGER NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoice_invoice_item FOREIGN KEY (invoice_id) REFERENCES invoice (id),
  CONSTRAINT track_invoice_item FOREIGN KEY (track_id) REFERENCES track (id)
) STRICT;

CREATE TABLE media_type(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL
) STRICT;

CREATE TABLE playlist(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE playlist_track(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  playlist_id INTEGER NOT NULL,
  track_id INTEGER NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT playlist_playlist_track
    FOREIGN KEY (playlist_id) REFERENCES playlist (id),
  CONSTRAINT track_playlist_track FOREIGN KEY (track_id) REFERENCES track (id)
) STRICT;

CREATE TABLE track(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  composer TEXT,
  millseconds INTEGER,
  bytes INTEGER NOT NULL,
  unit_price INTEGER NOT NULL,
  album_id INTEGER NOT NULL,
  media_type_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT album_track FOREIGN KEY (album_id) REFERENCES album (id),
  CONSTRAINT media_type_track
    FOREIGN KEY (media_type_id) REFERENCES media_type (id),
  CONSTRAINT genre_track FOREIGN KEY (genre_id) REFERENCES genre (id)
) STRICT;
